{
  "uid" : "1ed3f19cfb7f35c7",
  "name" : "test_login_failed[data2]",
  "fullName" : "cases.test_login.TestLogin#test_login_failed",
  "historyId" : "daee70692129a544e4ece7a1edb1fbca",
  "time" : {
    "start" : 1614504768964,
    "stop" : 1614504773642,
    "duration" : 4678
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "prepare_to_login",
    "time" : {
      "start" : 1614504744571,
      "stop" : 1614504756347,
      "duration" : 11776
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "handler",
    "time" : {
      "start" : 1614504724559,
      "stop" : 1614504744571,
      "duration" : 20012
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "__pytest_repeat_step_number",
    "time" : {
      "start" : 1614504768964,
      "stop" : 1614504768964,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "agree_the_privacy",
    "time" : {
      "start" : 1614504756347,
      "stop" : 1614504759396,
      "duration" : 3049
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "fb8058c398a17b39",
      "name" : "log",
      "source" : "fb8058c398a17b39.txt",
      "type" : "text/plain",
      "size" : 5390
    } ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "handler::0",
    "time" : {
      "start" : 1614504787675,
      "stop" : 1614504788169,
      "duration" : 494
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('prepare_to_login')"
  }, {
    "name" : "parentSuite",
    "value" : "cases"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "ruslan"
  }, {
    "name" : "thread",
    "value" : "14824-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "cases.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "data",
    "value" : "{'name': '登录功能-异常登录-用户名错误', 'username': '15566669999', 'password': '654321Ok', 'error_msg': '用户不存在'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "18fac21135c263a1",
      "status" : "passed",
      "time" : {
        "start" : 1614504167406,
        "stop" : 1614504175089,
        "duration" : 7683
      }
    }, {
      "uid" : "baaf24e39a17208f",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CE860D9B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",
      "time" : {
        "start" : 1614499960998,
        "stop" : 1614499960998,
        "duration" : 0
      }
    }, {
      "uid" : "912de4cd0906d334",
      "status" : "passed",
      "time" : {
        "start" : 1610872609788,
        "stop" : 1610872614416,
        "duration" : 4628
      }
    }, {
      "uid" : "c786025395b7631b",
      "status" : "passed",
      "time" : {
        "start" : 1610870718067,
        "stop" : 1610870722819,
        "duration" : 4752
      }
    }, {
      "uid" : "e49a4f23eb57360c",
      "status" : "broken",
      "statusDetails" : "TypeError: 'Log' object is not callable",
      "time" : {
        "start" : 1610870401371,
        "stop" : 1610870415017,
        "duration" : 13646
      }
    }, {
      "uid" : "6e9407ec122dacc1",
      "status" : "passed",
      "time" : {
        "start" : 1610868187358,
        "stop" : 1610868192132,
        "duration" : 4774
      }
    } ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.usefixtures('prepare_to_login')" ]
  },
  "source" : "1ed3f19cfb7f35c7.json",
  "parameterValues" : [ "{'name': '登录功能-异常登录-用户名错误', 'username': '15566669999', 'password': '654321Ok', 'error_msg': '用户不存在'}" ]
}