{
  "uid" : "54dc508b8a02d917",
  "name" : "test_login_failed[data1]",
  "fullName" : "cases.test_login.TestLogin#test_login_failed",
  "historyId" : "28fbee3f7849e5c692210a9f12e7fe96",
  "time" : {
    "start" : 1614504764236,
    "stop" : 1614504768960,
    "duration" : 4724
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "prepare_to_login",
    "time" : {
      "start" : 1614504744571,
      "stop" : 1614504756347,
      "duration" : 11776
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "handler",
    "time" : {
      "start" : 1614504724559,
      "stop" : 1614504744571,
      "duration" : 20012
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "agree_the_privacy",
    "time" : {
      "start" : 1614504756347,
      "stop" : 1614504759396,
      "duration" : 3049
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "__pytest_repeat_step_number",
    "time" : {
      "start" : 1614504764235,
      "stop" : 1614504764235,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "2736aacea16503cf",
      "name" : "log",
      "source" : "2736aacea16503cf.txt",
      "type" : "text/plain",
      "size" : 5354
    } ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "handler::0",
    "time" : {
      "start" : 1614504787675,
      "stop" : 1614504788169,
      "duration" : 494
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('prepare_to_login')"
  }, {
    "name" : "parentSuite",
    "value" : "cases"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "ruslan"
  }, {
    "name" : "thread",
    "value" : "14824-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "cases.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "data",
    "value" : "{'name': '登录功能-异常登录-用户名错误', 'username': 'abc', 'password': '654321Ok', 'error_msg': '账号或密码错误'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "18549c3379dabdd5",
      "status" : "broken",
      "statusDetails" : "TypeError: 'Log' object is not callable",
      "time" : {
        "start" : 1614504151584,
        "stop" : 1614504167318,
        "duration" : 15734
      }
    }, {
      "uid" : "6bb88027ec65e189",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CE860D9B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))",
      "time" : {
        "start" : 1614499960838,
        "stop" : 1614499960838,
        "duration" : 0
      }
    }, {
      "uid" : "f1e6e1e9c9115027",
      "status" : "passed",
      "time" : {
        "start" : 1610872605180,
        "stop" : 1610872609782,
        "duration" : 4602
      }
    }, {
      "uid" : "d5114d3dd247e331",
      "status" : "passed",
      "time" : {
        "start" : 1610870713255,
        "stop" : 1610870718060,
        "duration" : 4805
      }
    }, {
      "uid" : "8e8fc3ff8b64a739",
      "status" : "broken",
      "statusDetails" : "TypeError: 'Log' object is not callable",
      "time" : {
        "start" : 1610870387649,
        "stop" : 1610870401178,
        "duration" : 13529
      }
    }, {
      "uid" : "98d8ba555614a2e3",
      "status" : "passed",
      "time" : {
        "start" : 1610868182600,
        "stop" : 1610868187349,
        "duration" : 4749
      }
    } ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.usefixtures('prepare_to_login')" ]
  },
  "source" : "54dc508b8a02d917.json",
  "parameterValues" : [ "{'name': '登录功能-异常登录-用户名错误', 'username': 'abc', 'password': '654321Ok', 'error_msg': '账号或密码错误'}" ]
}