{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "657b50bf-70e0-4aaa-84d8-abf1f8bb9810-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-密码为空', 'username': '15510817996', 'password': '', 'error_msg': '密码不能为空'}"}], "start": 1614504175096, "stop": 1614504182891, "uuid": "0899f082-6a9b-411a-905d-00297c2bcef1", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('prepare_to_login')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "2836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}