{"name": "test_login_failed[data2]", "status": "passed", "attachments": [{"name": "log", "source": "9bd728ca-ee56-41a0-a123-41a18b8c14b1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-用户名错误', 'username': '15566669999', 'password': '654321Ok', 'error_msg': '用户不存在'}"}], "start": 1610868187358, "stop": 1610868192132, "uuid": "718ba6c7-77bb-4df4-996b-07538aded39b", "historyId": "daee70692129a544e4ece7a1edb1fbca", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('prepare_to_login')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "15284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}