{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "7103eef9-a65e-4e11-aa61-96ff61b895b4-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-密码为空', 'username': '15510817996', 'password': '', 'error_msg': '密码不能为空'}"}], "start": 1610870415134, "stop": 1610870419796, "uuid": "171711eb-005e-4dda-a3a1-985a4a83c87e", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('prepare_to_login')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "8844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}