{"name": "test_login_failed[data1]", "status": "passed", "attachments": [{"name": "log", "source": "e3841e5c-b092-46ee-a2a4-f64aa895bc49-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-用户名错误', 'username': 'abc', 'password': '654321Ok', 'error_msg': '账号或密码错误'}"}], "start": 1610870713255, "stop": 1610870718060, "uuid": "57196751-b9d3-42a2-952f-6238ad17b81c", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('prepare_to_login')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "10788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}